config/routes.rb
Rails.application.routes.draw do
  resources :lyn_ins
  match '/lyn_ins/:id/new_play(.:format)' => "lyn_ins#new_play", :via => :get

  root 'lyn_ins#index'
  resource :users

end

app/models/User.rb
class User < ActiveRecord::Base
end

app/models/lyn_in.rb
class LynIn < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lyn_ins_controller.rb
class LynInsController < ApplicationController
  before_action :set_lyn_in, only: [:show, :edit, :update, :destroy]

  # GET /lyn_ins
  # GET /lyn_ins.json
  def index
    @lyn_ins = LynIn.all
  end

  # GET /lyn_ins/1
  # GET /lyn_ins/1.json
  def show
  end

  # GET /lyn_ins/new
  def new
    @lyn_in = LynIn.new
  end

  # GET /lyn_ins/1/edit
  def edit
  end

  # POST /lyn_ins
  # POST /lyn_ins.json
  def create
    @lyn_in = LynIn.new(lyn_in_params)
    @lyn_in.avatar = params[:lyn_in][:avatar]
    respond_to do |format|
      if @lyn_in.save
        format.html { redirect_to @lyn_in, notice: 'Lyn in was successfully created.' }
        format.json { render :show, status: :created, location: @lyn_in }
      else
        format.html { render :new }
        format.json { render json: @lyn_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lyn_ins/1
  # PATCH/PUT /lyn_ins/1.json
  def update
    respond_to do |format|
      if @lyn_in.update(lyn_in_params)
        format.html { redirect_to @lyn_in, notice: 'Lyn in was successfully updated.' }
        format.json { render :show, status: :ok, location: @lyn_in }
      else
        format.html { render :edit }
        format.json { render json: @lyn_in.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_play
   set_lyn_in
    @lyn_in.avatar.url
  end

  # DELETE /lyn_ins/1
  # DELETE /lyn_ins/1.json
  def destroy
    @lyn_in.destroy
    respond_to do |format|
      format.html { redirect_to lyn_ins_url, notice: 'Lyn in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lyn_in
      @lyn_in = LynIn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lyn_in_params
      params.require(:lyn_in).permit(:name, :score, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @person = User.new
  end

  def create
    binding.pry
    @person = User.new(params[:users])
    @person.save
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lyn_ins_helper.rb
module LynInsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lyn" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Lyn</a>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>

            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/lyn_ins/_form.html.erb
<%= form_for @lyn_in, :html => { :class => "form-horizontal lyn_in" , :multipart=>true} do |f| %>

  <% if @lyn_in.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@lyn_in.errors.count, "error") %> prohibited this lyn_in from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @lyn_in.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :score, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :score, :class => 'form-control' %>
    </div>
    <%=f.error_span(:score) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
    <%= f.file_field :avatar  %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lyn_ins_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/lyn_ins/edit.html.erb
<%- model_class = LynIn -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lyn_ins/index.html.erb
<%- model_class = LynIn -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:score) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:avatar) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lyn_ins.each do |lyn_in| %>
      <tr>
        <td><%= link_to lyn_in.id, lyn_in_path(lyn_in) %></td>
        <td><%= lyn_in.name %></td>
        <td><%= lyn_in.score %></td>
        <td><%= lyn_in.description %></td>
        <td><%= lyn_in.avatar_identifier %></td>
        <td>
          <%= link_to "play", {:controller => "lyn_ins",:id=>lyn_in.id, :action => "new_play"}%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_lyn_in_path(lyn_in), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      lyn_in_path(lyn_in),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_lyn_in_path,
            :class => 'btn btn-primary' %>

app/views/lyn_ins/new.html.erb
<%- model_class = LynIn -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lyn_ins/new_play.erb
<head>
  <%= stylesheet_link_tag "plyr" %>
  <%= javascript_include_tag "plyr" %>
</head>
<body>
<header>
</header>
<main role="main" id="main">

    <div class="player">
      <video poster="<%= image_path "timg.jpg" %>" controls crossorigin>
        <!-- 视频文件 -->
        <source src="<%= @lyn_in.avatar.url %>" type="video/mp4">
        <!-- 针对不支持 <video> 元素的兼容 -->
        <a href="<%= @lyn_in.avatar.url %>">Download</a>
      </video>
    </div>

</main>

<script src="https://cdn.rangetouch.com/0.0.9/rangetouch.js" async></script>

<!-- Sharing libary (https://shr.one) -->
<script src="https://cdn.shr.one/0.1.9/shr.js"></script>
<script>
   plyr.setup();
 </script>
</body>

app/views/lyn_ins/show.html.erb
<%- model_class = LynIn -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @lyn_in.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:score) %>:</strong></dt>
  <dd><%= @lyn_in.score %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @lyn_in.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              lyn_ins_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lyn_in_path(@lyn_in), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lyn_in_path(@lyn_in),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/users/new.erb
<%= form_for @person,url: @person_path,method: :post do |f| %>

    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%=f.error_span(:name) %>
    </div>
    <div class="form-group">
      <%= f.label :password, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.password_field :password, :class => 'form-control' %>
      </div>
      <%=f.error_span(:password) %>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    root_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>